(function (angular) {
  "use strict";
  angular.module('app').factory('HomeService', HomeService);

  HomeService.$inject = [];

  function HomeService() {
    var movies =
        {
        "dates": {
        "minimum": "2015-06-03",
        "maximum": "2015-07-15"
        },
        "page": 1,
        "results": [
        {
        "adult": false,
        "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
        "genre_ids": [28,12,878,53],
        "id": 135397,
        "original_language": "en",
        "original_title": "1Jurassic World",
        "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
        "release_date": "2015-06-12",
        "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
        "popularity": 54.349781,
        "title": "Jurassic World",
        "video": false,
        "vote_average": 7,
        "vote_count": 910},
        {
        "adult": false,
        "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
        "genre_ids": [878,28,53,12],
        "id": 87101,
        "original_language": "en",
        "original_title": "Terminator Genisys",
        "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
        "release_date": "2015-07-01",
        "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
        "popularity": 50.258717,
        "title": "Terminator Genisys",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 168
        },
        {
        "adult": false,
        "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
        "genre_ids": [28,12,878,53],
        "id": 135397,
        "original_language": "en",
        "original_title": "Jurassic World",
        "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
        "release_date": "2015-06-12",
        "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
        "popularity": 54.349781,
        "title": "Jurassic World",
        "video": false,
        "vote_average": 7,
        "vote_count": 910},
        {
        "adult": false,
        "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
        "genre_ids": [878,28,53,12],
        "id": 87101,
        "original_language": "en",
        "original_title": "Terminator Genisys",
        "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
        "release_date": "2015-07-01",
        "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
        "popularity": 50.258717,
        "title": "Terminator Genisys",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 168
        },
        {
        "adult": false,
        "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
        "genre_ids": [28,12,878,53],
        "id": 135397,
        "original_language": "en",
        "original_title": "Jurassic World",
        "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
        "release_date": "2015-06-12",
        "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
        "popularity": 54.349781,
        "title": "Jurassic World",
        "video": false,
        "vote_average": 7,
        "vote_count": 910},
        {
        "adult": false,
        "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
        "genre_ids": [878,28,53,12],
        "id": 87101,
        "original_language": "en",
        "original_title": "Terminator Genisys",
        "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
        "release_date": "2015-07-01",
        "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
        "popularity": 50.258717,
        "title": "Terminator Genisys",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 168
        },
        {
        "adult": false,
        "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
        "genre_ids": [28,12,878,53],
        "id": 135397,
        "original_language": "en",
        "original_title": "Jurassic World",
        "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
        "release_date": "2015-06-12",
        "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
        "popularity": 54.349781,
        "title": "Jurassic World",
        "video": false,
        "vote_average": 7,
        "vote_count": 910},
        {
        "adult": false,
        "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
        "genre_ids": [878,28,53,12],
        "id": 87101,
        "original_language": "en",
        "original_title": "Terminator Genisys",
        "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
        "release_date": "2015-07-01",
        "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
        "popularity": 50.258717,
        "title": "Terminator Genisys",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 168
        },
        {
        "adult": false,
        "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
        "genre_ids": [28,12,878,53],
        "id": 135397,
        "original_language": "en",
        "original_title": "Jurassic World",
        "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
        "release_date": "2015-06-12",
        "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
        "popularity": 54.349781,
        "title": "Jurassic World",
        "video": false,
        "vote_average": 7,
        "vote_count": 910},
        {
        "adult": false,
        "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
        "genre_ids": [878,28,53,12],
        "id": 87101,
        "original_language": "en",
        "original_title": "Terminator Genisys",
        "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
        "release_date": "2015-07-01",
        "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
        "popularity": 50.258717,
        "title": "Terminator Genisys",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 168
        },
        {
        "adult": false,
        "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
        "genre_ids": [28,12,878,53],
        "id": 135397,
        "original_language": "en",
        "original_title": "Jurassic World",
        "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
        "release_date": "2015-06-12",
        "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
        "popularity": 54.349781,
        "title": "Jurassic World",
        "video": false,
        "vote_average": 7,
        "vote_count": 910},
        {
        "adult": false,
        "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
        "genre_ids": [878,28,53,12],
        "id": 87101,
        "original_language": "en",
        "original_title": "Terminator Genisys",
        "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
        "release_date": "2015-07-01",
        "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
        "popularity": 50.258717,
        "title": "Terminator Genisys",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 168
        },
        {
        "adult": false,
        "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
        "genre_ids": [28,12,878,53],
        "id": 135397,
        "original_language": "en",
        "original_title": "2Jurassic World",
        "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
        "release_date": "2015-06-12",
        "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
        "popularity": 54.349781,
        "title": "Jurassic World",
        "video": false,
        "vote_average": 7,
        "vote_count": 910},
        {
        "adult": false,
        "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
        "genre_ids": [878,28,53,12],
        "id": 87101,
        "original_language": "en",
        "original_title": "Terminator Genisys",
        "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
        "release_date": "2015-07-01",
        "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
        "popularity": 50.258717,
        "title": "Terminator Genisys",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 168
        },
        {
        "adult": false,
        "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
        "genre_ids": [28,12,878,53],
        "id": 135397,
        "original_language": "en",
        "original_title": "Jurassic World",
        "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
        "release_date": "2015-06-12",
        "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
        "popularity": 54.349781,
        "title": "Jurassic World",
        "video": false,
        "vote_average": 7,
        "vote_count": 910},
        {
        "adult": false,
        "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
        "genre_ids": [878,28,53,12],
        "id": 87101,
        "original_language": "en",
        "original_title": "Terminator Genisys",
        "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
        "release_date": "2015-07-01",
        "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
        "popularity": 50.258717,
        "title": "Terminator Genisys",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 168
        },
        {
        "adult": false,
        "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
        "genre_ids": [28,12,878,53],
        "id": 135397,
        "original_language": "en",
        "original_title": "Jurassic World",
        "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
        "release_date": "2015-06-12",
        "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
        "popularity": 54.349781,
        "title": "Jurassic World",
        "video": false,
        "vote_average": 7,
        "vote_count": 910},
        {
        "adult": false,
        "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
        "genre_ids": [878,28,53,12],
        "id": 87101,
        "original_language": "en",
        "original_title": "Terminator Genisys",
        "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
        "release_date": "2015-07-01",
        "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
        "popularity": 50.258717,
        "title": "Terminator Genisys",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 168
        },
        {
        "adult": false,
        "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
        "genre_ids": [28,12,878,53],
        "id": 135397,
        "original_language": "en",
        "original_title": "Jurassic World",
        "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
        "release_date": "2015-06-12",
        "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
        "popularity": 54.349781,
        "title": "Jurassic World",
        "video": false,
        "vote_average": 7,
        "vote_count": 910},
        {
        "adult": false,
        "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
        "genre_ids": [878,28,53,12],
        "id": 87101,
        "original_language": "en",
        "original_title": "Terminator Genisys",
        "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
        "release_date": "2015-07-01",
        "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
        "popularity": 50.258717,
        "title": "Terminator Genisys",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 168
        },
        {
        "adult": false,
        "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
        "genre_ids": [28,12,878,53],
        "id": 135397,
        "original_language": "en",
        "original_title": "Jurassic World",
        "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
        "release_date": "2015-06-12",
        "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
        "popularity": 54.349781,
        "title": "Jurassic World",
        "video": false,
        "vote_average": 7,
        "vote_count": 910},
        {
        "adult": false,
        "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
        "genre_ids": [878,28,53,12],
        "id": 87101,
        "original_language": "en",
        "original_title": "Terminator Genisys",
        "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
        "release_date": "2015-07-01",
        "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
        "popularity": 50.258717,
        "title": "Terminator Genisys",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 168
        },
        {
        "adult": false,
        "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
        "genre_ids": [28,12,878,53],
        "id": 135397,
        "original_language": "en",
        "original_title": "Jurassic World",
        "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
        "release_date": "2015-06-12",
        "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
        "popularity": 54.349781,
        "title": "Jurassic World",
        "video": false,
        "vote_average": 7,
        "vote_count": 910},
        {
        "adult": false,
        "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
        "genre_ids": [878,28,53,12],
        "id": 87101,
        "original_language": "en",
        "original_title": "Terminator Genisys",
        "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
        "release_date": "2015-07-01",
        "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
        "popularity": 50.258717,
        "title": "Terminator Genisys",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "3Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "4Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "5Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "6Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
      },
      {
      "adult": false,
      "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
      "genre_ids": [28,12,878,53],
      "id": 135397,
      "original_language": "en",
      "original_title": "Jurassic World",
      "overview": "Twenty-two years after the events of Jurassic Park,   Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
      "release_date": "2015-06-12",
      "poster_path": "/uXZYawqUsChGSj54wcuBtEdUJbh.jpg",
      "popularity": 54.349781,
      "title": "Jurassic World",
      "video": false,
      "vote_average": 7,
      "vote_count": 910},
      {
      "adult": false,
      "backdrop_path": "/o4I5sHdjzs29hBWzHtS2MKD3JsM.jpg",
      "genre_ids": [878,28,53,12],
      "id": 87101,
      "original_language": "en",
      "original_title": "last Terminator Genisys",
      "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
      "release_date": "2015-07-01",
      "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
      "popularity": 50.258717,
      "title": "Terminator Genisys",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 168
    }]
    }

  return {
    movies: movies
  };
}

})
(angular);
